### ISSUE TITLE
Missing images in Tumbleweed theme

### ISSUE THREAD

**Issue by DimStar77** [kwwii/raw-theme-drop#1]
I started (finally) to look into adjusting our branding package for Tumbleweed - long overdue.

I started to base my work on the existing Leap package (which should be a good base) - there is a raw-drop-folder where the raw images from your repo can just be added.

Sadly, it seems that on Leap there are more images available than for TW.

For example, TW is missing raw-theme-drop/grub-boot-1440x1080.png

Is that intentional? Can this be aligned between what was done for Leap and what we want to do for TW?

**Comment by DimStar77** [comment]
Seems those are the ones that were also added in a later commit to the leap directory, as requested by @coolo, but the TW drop in did not get the additional sizes.

**Comment by coolo** [comment]
use the leap versions where you miss TW versions - and make a complete list.

**Comment by DimStar77** [comment]
Of the ones that are actually referenced in the Makefile (and thus make it into the final tarball used for the actual branding package, I miss):

* desktop-1280x1024.png
* desktop-1600x1200.png
* install-boot-800x600.png
* plymouth-1200x1000.png
* tumbleweed-logo.png
